#Algoritmos Supervisados

#KNN

In [ ]:
import numpy as np
import pandas as pd
#modelo de clasificacion de KNN
from sklearn.neighbors import KNeighborsClassifier
#para dividir el dataset en entrenamiento y test
from sklearn.model_selection import train_test_split
#para obtener la matriz de confusion
from sklearn.metrics import confusion_matrix

In [ ]:
#datos=pd.read_csv("Product.csv")
#datos

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
datos=pd.read_csv("/gdrive/MyDrive/Datasets/Product.csv")
datos

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

* Age, EstimatedSalary-> regresion(2 continuas)
* Gender, Purchased-->clasificar(2 continuas y disc)


In [ ]:
#variables independientes
datosX=datos.iloc[:,[2,3]].values
datosX

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01, 2.80e+04],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [ ]:
#clasificador-Variable dependiente
datosY=datos.iloc[:,[4]].values
datosY

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [ ]:
X_e,X_p,Y_e,Y_p=train_test_split(datosX,datosY,test_size=0.3)

In [ ]:
#datos de X para entrenar
np.shape(X_e)

(320, 2)

In [ ]:
np.shape(Y_e)

(320, 1)

In [ ]:
#datos de X para probar
np.shape(X_p)

(120, 2)

##Experimentación 1

In [ ]:
#probando con los vecinos mas cercanos
modelo=KNeighborsClassifier(n_neighbors=3)
np.random.seed(2021)
#El ajuste de modelo de entrenamiento de KNN
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
#datos que predice
#y_predict
#datos de prueba para comprobar
#Y_p

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


In [ ]:
confusion_matrix(Y_p,y_predict)

array([[64, 11],
       [15, 30]])

#Experimentacion 2

In [ ]:
from sklearn.preprocessing import StandardScaler
escalado=StandardScaler()
datosXesc=escalado.fit_transform(datosX)
np.random.seed(2021)
X_e,X_p,Y_e,Y_p=train_test_split(datosXesc,datosY,test_size=0.2)
#probando con los vecinos mas cercanos
modelo=KNeighborsClassifier(n_neighbors=4, metric='euclidean')
#El ajuste de modelo de entrenamiento de KNN
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
confusion_matrix(Y_p,y_predict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':


array([[45,  4],
       [ 3, 28]])

#Experimentación 3

In [ ]:
from sklearn.preprocessing import StandardScaler
escalado=StandardScaler()
datosXesc=escalado.fit_transform(datosX)
np.random.seed(2021)
X_e,X_p,Y_e,Y_p=train_test_split(datosXesc,datosY,test_size=0.3)
#probando con los vecinos mas cercanos
modelo=KNeighborsClassifier(n_neighbors=4, metric='manhattan')
#El ajuste de modelo de entrenamiento de KNN
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
m=confusion_matrix(Y_p,y_predict)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':


In [ ]:
X_e.shape

(280, 2)

###determinando el ajuste

In [ ]:
#precision para los compradores
100*m[0,0]/(m[0,0]+m[0,1])

89.47368421052632

In [ ]:
#precision para los no compradores
100*m[1,1]/(m[1,0]+m[1,1])

81.81818181818181

##Tarea
* aplicación e interpretación de las métricas de similaridad de Minkosky-malahanobis-coseno-jakard
* Estudiar Regresión con Gradiente descedente

#SVM

In [ ]:
import numpy as np
import pandas as pd
#modelo de clasificacion de SVM
from sklearn.svm import SVC
#para dividir el dataset en entrenamiento y test
from sklearn.model_selection import train_test_split
#para obtener la matriz de confusion
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.preprocessing import StandardScaler
escalado=StandardScaler()
datosXesc=escalado.fit_transform(datosX)
np.random.seed(2021)
X_e,X_p,Y_e,Y_p=train_test_split(datosXesc,datosY,test_size=0.3)
#probando con los vecinos mas cercanos
modelo=SVC(kernel="linear")
#El ajuste de modelo de entrenamiento de KNN
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
m=confusion_matrix(Y_p,y_predict)
m

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[67,  9],
       [ 5, 39]])

In [ ]:
#precision para los compradores
100*m[0,0]/(m[0,0]+m[0,1])


88.15789473684211

In [ ]:
#precision para los no compradores
100*m[1,1]/(m[1,0]+m[1,1])

88.63636363636364

#Para kernel radial

###Experimentacion 1

In [ ]:
from sklearn.preprocessing import StandardScaler
escalado=StandardScaler()
datosXesc=escalado.fit_transform(datosX)
np.random.seed(2021)#uso de la misma semilla
X_e,X_p,Y_e,Y_p=train_test_split(datosXesc,datosY,test_size=0.3)
#probando con los vecinos mas cercanos
modelo=SVC(kernel="rbf")
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
m=confusion_matrix(Y_p,y_predict)
m

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[69,  7],
       [ 3, 41]])

In [ ]:
#precision para los compradores
100*m[0,0]/(m[0,0]+m[0,1])


90.78947368421052

In [ ]:
#precision para los no compradores
100*m[1,1]/(m[1,0]+m[1,1])

93.18181818181819

###Experimentacion 2

In [ ]:
from sklearn.preprocessing import StandardScaler
escalado=StandardScaler()
datosXesc=escalado.fit_transform(datosX)
np.random.seed(2021)
X_e,X_p,Y_e,Y_p=train_test_split(datosXesc,datosY,test_size=0.2)
#probando con los vecinos mas cercanos
modelo=SVC(kernel="rbf")
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
m=confusion_matrix(Y_p,y_predict)
m

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[45,  4],
       [ 3, 28]])

In [ ]:
#precision para los compradores
100*m[0,0]/(m[0,0]+m[0,1])

91.83673469387755

In [ ]:
#precision para los no compradores
100*m[1,1]/(m[1,0]+m[1,1])

90.3225806451613

In [ ]:
m[1,0]+m[1,1]+m[0,0]+m[0,1]

80

###Experimentacion 3

In [ ]:
from sklearn.preprocessing import StandardScaler
escalado=StandardScaler()
datosXesc=escalado.fit_transform(datosX)
np.random.seed(2021)
X_e,X_p,Y_e,Y_p=train_test_split(datosXesc,datosY,test_size=0.1)
#probando con los vecinos mas cercanos
modelo=SVC(kernel="poly", degree=5)
modelo.fit(X_e,Y_e)
y_predict=modelo.predict(X_p)
m=confusion_matrix(Y_p,y_predict)
m

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[24,  2],
       [ 3, 11]])

In [ ]:
#precision para los compradores
100*m[0,0]/(m[0,0]+m[0,1])
#sobreajuste

92.3076923076923

In [ ]:
#precision para los no compradores
100*m[1,1]/(m[1,0]+m[1,1])

78.57142857142857

#Trabajo Domiciliario
* experimentar usando el método de codo
* modificar las experimentaciones en un ciclo repetitivo para determinar el mejor ajuste
* Resumen de arboles de decision y randomForest, considerar profundida, gini


* ideas de proyectos de aprendizaje por reforzamiento 